spring.application.name=club-employee-control

server.port=8081
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.operationsSorter=method
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100
spring.web.resources.add-mappings=false
spring.jpa.open-in-view=false
springdoc.model-converters.pageable-converter.enabled=true
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
